name: Check Main

on:
  push:
    branches:
      - main

jobs:
  check-main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Flake8 and Unittest
      run: |
        pip install flake8
        pip install unittest

    - name: Display Python version
      run: python --version

    - name: Run Flake8
      run: flake8

    - name: Run Unittest
      run: python -m unittest discover -s . -p 'test*.py
